name: Vinted Bot

on:
  schedule:
    - cron: "*/5 * * * *" # Runs the bot every 5 minutes
  workflow_dispatch: # Allow manual trigger

concurrency:
  group: vinted-scraper
  cancel-in-progress: true  # Ensures a new run starts every 5 mins, even if the previous one is still running

jobs:
  run_bot:
    runs-on: ubuntu-latest # Runs on a fresh Ubuntu server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Choose Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the Vinted Bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Load the secret here
        run: |
          python app.py
